---
- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - MySQL-python

- name: Start MariaDB
  service: name=mariadb state=started enabled=yes

- name: Set Password for root user
  mysql_user: name=root password={{ mysql_root_passwd }}

- name: Setup the .my.cnf file for root user
  template: src=mycnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
