---

- name: Create Designate Service User in Keystone
  environment: keystone_env
  shell: openstack user create --password designate designate
  ignore_errors: true

- name: Assign Designate Keystone User to Service Tenant
  environment: keystone_env
  shell: openstack role add --project service --user designate admin 
  ignore_errors: true

- name: Create Designate Service in keystone catalog
  environment: keystone_env
  shell: openstack service create --name designate --description "OpenStack DNS" dns
  ignore_errors: true

- name: Create designate endpoint
  environment: keystone_env
  shell: openstack endpoint create --publicurl http://{{inventory_hostname}}:9001/v1 --internalurl http://{{inventory_hostname}}:9001/v1 --adminurl http://{{inventory_hostname}}:9001/v1 dns
  ignore_errors: true

- name: Create Designate Database
  mysql_db: name={{ designate_db }} state=present encoding=utf8

- name: Create Designate Pool Database
  mysql_db: name={{ designate_pooldb }} state=present encoding=utf8

- name: Create Desigante MariaDB account and setup permissions
  mysql_user: name={{ mysql_designate_user }} password={{ mysql_designate_passwd }} priv={{ designate_db }}.*:ALL/{{ designate_pooldb }}.*:ALL state=present

- name: Create Designate RabbitMQ account and setup permissions
  rabbitmq_user: user={{rabbitmq_designate_user}}
                 password={{rabbitmq_designate_passwd}}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: Install designate
  yum: name={{item}} state=present
  with_items:
    - python-designateclient
    - openstack-designate-pool-manager
    - openstack-designate-mdns
    - openstack-designate-common
    - openstack-designate-central
    - openstack-designate-api
    - python-tooz
    - python2-oslo-reports
    - python-suds

- name: Install designate template
  template: src=designate.conf.j2 dest=/etc/designate/designate.conf

- name: Install designate pool config
  template: src=pools.yaml.j2 dest=/etc/designate/pools.yaml

- name: Install Designate Database
  command: designate-manage database sync

- name: Install Designate_Pool Database
  command: designate-manage pool-manager-cache sync

- name: Launch Designate Central
  service: name=designate-central state=started enabled=yes

- name: Launch Designate API
  service: name=designate-api state=started enabled=yes

- name: Launch Designate MDNS
  service: name=designate-mdns state=started enabled=yes

- name: Update Pool
  command: designate-manage pool update

- name: Launch Designate Pool-Manager
  service: name=designate-pool-manager state=started enabled=yes

- name: Grab pool id
  shell: designate-manage pool show_config | grep id | awk '{print $2}'
  register: pool_id

- name: Sync Slaves
  command: designate-manage powerdns sync {{ pool_id.stdout }}

- name: Create the Designate User
  environment: keystone_env
  shell: openstack user create --password {{ designate_os_password }} {{ designate_os_user }}

- name: Create Designate User tenant
  environment: keystone_env
  shell: openstack project create --description="Designate Test Tenant" {{ designate_os_tenant }}

- name: Assign Designate User to 
  environment: keystone_env
  shell: openstack role add --project {{ designate_os_tenant }} --user {{ designate_os_user }} member

- name: Create a RC file for Designate Creds
  template: src=rc.j2 dest=/root/designate-test.rc
